#!/bin/bash

echo -e "\e[92m Checking if PHP package is installed... \e[0m";

(php --version) && echo -e "\e[32m PHP is installed correctly, executing the script....\n Creating server on $1\e[0m" && php -S $1 -t $2 || echo -e "\e[31m The script didnt create the server, because there was an error during exexecuting, check if you have got PHP package by writing: \n sudo apt show -- if not try commands below: \n sudo apt-get update | sudo apt-get install php \e[0m" && exit;

